import { CheckCircle2, Clock3, ListTodo, TrendingUp } from 'lucide-react';
import type { DailySummary } from '@/models';
import { formatDuration } from '@/utils/format';
import { Icon } from '@/components/ui/Icon';

export function SummaryPanel({ summary }: { summary: DailySummary | null }) {
  if (!summary) return <div className="empty-state"><Clock3/><h3>Your daily story starts here</h3><p>Track a task and your focus pattern will appear.</p></div>;
  const max = Math.max(...summary.tasksWorkedOn.map((item) => item.seconds), 1);
  return <div className="summary-layout"><section className="metrics-grid"><article className="metric-card metric-featured"><div className="metric-icon"><Icon icon={Clock3}/></div><span>Focused today</span><strong>{formatDuration(summary.totalSeconds, true)}</strong><small>Live total for your local day</small></article><article className="metric-card"><div className="metric-icon"><Icon icon={CheckCircle2}/></div><span>Completed</span><strong>{summary.completedCount}</strong><small>Tasks crossed off today</small></article><article className="metric-card"><div className="metric-icon"><Icon icon={TrendingUp}/></div><span>In progress</span><strong>{summary.inProgressCount}</strong><small>Tasks with momentum</small></article><article className="metric-card"><div className="metric-icon"><Icon icon={ListTodo}/></div><span>Still pending</span><strong>{summary.pendingCount}</strong><small>Ready when you are</small></article></section><section className="focus-breakdown surface"><div className="section-heading"><div><span className="eyebrow">Focus distribution</span><h2>Where your time went</h2></div><span className="date-chip">Today</span></div>{summary.tasksWorkedOn.length ? <div className="bar-list">{summary.tasksWorkedOn.map((item, index) => <div className="bar-row" key={item.taskId}><div className="bar-label"><span><b>{String(index + 1).padStart(2, '0')}</b>{item.title}</span><strong>{formatDuration(item.seconds, true)}</strong></div><div className="bar-track"><div className="bar-fill" style={{ width: `${Math.max(4, item.seconds / max * 100)}%` }}/></div></div>)}</div> : <div className="inline-empty">No tracked sessions yet. Start a timer to build today’s focus map.</div>}</section></div>;
}
