import { useState } from 'react';
import { Navigate, Link, useNavigate, useParams } from 'react-router-dom';
import { ArrowRight, Eye, EyeOff, ShieldCheck, Sparkles, Timer } from 'lucide-react';
import { useAuth } from '@/controllers/auth.controller';
import { Icon } from '@/components/ui/Icon';

export function AuthView() {
  const { mode = 'login' } = useParams(); const signupMode = mode === 'signup'; const { user, loading, login, signup } = useAuth(); const navigate = useNavigate(); const [show, setShow] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  if (!loading && user) return <Navigate to="/app" replace />;
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(''); const form = Object.fromEntries(new FormData(event.currentTarget)) as Record<string, string>; try { if (signupMode) await signup({ name: form.name, email: form.email, password: form.password }); else await login({ email: form.email, password: form.password }); navigate('/app'); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to continue.'); } finally { setBusy(false); } }
  return <main className="auth-page"><section className="auth-story"><div className="brand"><span className="brand-mark"><Icon icon={Timer} size={21} /></span><span>tempo</span></div><div className="story-content"><span className="eyebrow">Your day, in focus</span><h1>Make time<br /><em>visible.</em></h1><p>Turn scattered intentions into focused work. Tempo gives every task a place and every minute a purpose.</p><div className="story-proof"><span><Icon icon={Sparkles} />Smart task refinement</span><span><Icon icon={ShieldCheck} />Private by design</span></div></div><div className="orb orb-one"/><div className="orb orb-two"/></section><section className="auth-panel"><div className="auth-card"><span className="auth-kicker">{signupMode ? 'Begin with clarity' : 'Welcome back'}</span><h2>{signupMode ? 'Build your focused workday.' : 'Pick up where you left off.'}</h2><p>{signupMode ? 'A calm, private workspace is a minute away.' : 'Sign in to see today’s progress.'}</p><form className="auth-form" onSubmit={submit} noValidate>{error && <div className="form-error" role="alert">{error}</div>}{signupMode && <label><span>Full name</span><input name="name" autoComplete="name" minLength={2} required placeholder="Alex Morgan" /></label>}<label><span>Email address</span><input name="email" type="email" autoComplete="email" required placeholder="you@company.com" /></label><label><span>Password</span><div className="password-field"><input name="password" type={show ? 'text' : 'password'} autoComplete={signupMode ? 'new-password' : 'current-password'} minLength={8} required placeholder="At least 8 characters"/><button type="button" className="icon-button" onClick={() => setShow(!show)} aria-label={show ? 'Hide password' : 'Show password'}><Icon icon={show ? EyeOff : Eye}/></button></div>{signupMode && <small>Use upper and lowercase letters and a number.</small>}</label><button className="primary-button auth-submit" disabled={busy}>{busy ? 'One moment…' : <>{signupMode ? 'Create free account' : 'Enter your workspace'}<Icon icon={ArrowRight}/></>}</button><p className="auth-switch">{signupMode ? 'Already have an account?' : 'New to Tempo?'} <Link to={signupMode ? '/auth/login' : '/auth/signup'}>{signupMode ? 'Sign in' : 'Create an account'}</Link></p></form></div><p className="auth-footnote">Thoughtful productivity, without the noise.</p></section></main>;
}
